### ISSUE TITLE
evaluate FedE

### ISSUE THREAD

**Issue by lihuiliullh** [zjukg/FedE#1]
I think the evaluation strategy used in FedE has a problem.
![image](https://user-images.githubusercontent.com/53407011/173448551-dc616ddb-4da6-49e5-a586-c01e1a34864a.png)

In the code, the final results are the weighted average of each client. But I think this is not appropriate. 
The correct way should be scoring by each client, and get the weighted score, and ranking by server and calculate the results.
Do you think it is correct?

**Comment by AnselCmy** [comment]
Thanks for reading our code! For your question, the process of "scoring by each client, and get the weighted score" is confusing for me, please give me a more clear expression if possible. 

The evaluation process in our code is reasonable, since each client has its own test set, and we conduct link prediction on test sets of all clients. Moreover, the "weighted average of each client" considers the number of test triples for each client.
